export const LOADING_ERROR = 'LOADING_ERROR';

export const CONFIG_LOAD = 'CONFIG_LOAD';
export const SET_DATA = 'SET_DATA';

export const CHANGE_THEME = 'CHANGE_THEME';
export const CHANGE_BACKGROUND = 'CHANGE_BACKGROUND';
export const CHANGE_BUTTON_COLOR = 'CHANGE_BUTTON_COLOR';

export const EDIT_BLOCK = 'EDIT_BLOCK';
export const REMOVE_BLOCK = 'REMOVE_BLOCK';

export const EDIT_MESSENGERS_DATA = 'EDIT_MESSENGERS_DATA';
export const EDIT_SOCIAL_DATA = 'EDIT_SOCIAL_DATA';

export const UPDATE_CONFIG_DATA = 'UPDATE_CONFIG_DATA';
